workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'develop'
          include: true
          source: true
        - pattern: 'release/*'
          include: true
          source: true
      tag_patterns:
        - pattern: 'v*.*.*'
          include: true
        - pattern: 'ios-v*'
          include: true
      cancel_previous_builds: true
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.aifun.dateideas.planadate
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean macOS metadata files
        script: |
          echo "Cleaning macOS metadata files..."
          find . -name "._*" -type f -delete
          find . -name ".DS_Store" -type f -delete
          echo "Cleanup complete"
          
      - name: Set up environment files
        script: |
          echo "Setting up environment files..."
          echo "DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY" > .env
          echo "FOURSQUARE_API_KEY=$FOURSQUARE_API_KEY" >> .env
          echo "ONESIGNAL_APP_ID=369027f2-a9c9-4c3c-9234-062e785220e1" >> .env
          cat .env
          
      - name: Verify Firebase config files
        script: |
          echo "Verifying Firebase configuration..."
          if [ -f "ios/Runner/GoogleService-Info.plist" ]; then
            echo "✅ GoogleService-Info.plist found"
            ls -la ios/Runner/GoogleService-Info.plist
          else
            echo "❌ Error: GoogleService-Info.plist not found"
            exit 1
          fi
          
      - name: Set up keychain
        script: |
          keychain initialize
          
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "com.aifun.dateideas.planadate" \
            --type IOS_APP_STORE \
            --create
            
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
          
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter --version
          flutter pub get
          flutter pub upgrade
      - name: Clean iOS build artifacts
        script: |
          cd ios
          rm -rf Pods Podfile.lock .symlinks
          cd ..
          flutter clean
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod --version
          pod repo update
          # Update specific pod causing conflict
          pod update GoogleUserMessagingPlatform
          # Install all pods
          pod install --repo-update --verbose
          cd ..
          
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos || true
          
      - name: Flutter build iOS
        script: |
          flutter build ipa --release \
            --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - anaskay.13@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false

  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: linux_x2
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'develop'
          include: true
          source: true
        - pattern: 'release/*'
          include: true
          source: true
      tag_patterns:
        - pattern: 'v*.*.*'
          include: true
        - pattern: 'android-v*'
          include: true
      cancel_previous_builds: true
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.aifun.dateideas.planadate"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up environment files
        script: |
          echo "Setting up secure files..."
          # Copy google-services.json if provided
          if [ ! -f "$CM_BUILD_DIR/android/app/google-services.json" ]; then
            echo "Warning: google-services.json not found"
          fi
          # Create .env file
          if [ -f "$CM_BUILD_DIR/.env" ]; then
            echo ".env file found"
          else
            echo "DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY" > .env
            echo "FOURSQUARE_API_KEY=$FOURSQUARE_API_KEY" >> .env
          fi
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter --version
          flutter pub get
          flutter pub upgrade
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos
      - name: Build Android APK
        script: |
          flutter build apk --release \
            --build-name=1.0.$BUILD_NUMBER
      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - anaskay.13@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
