// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC65YBtYjXJF2_tg_w149FK7Hz6Q9WRRhg',
    appId: '1:543297399935:web:911b9f15200cdbe95da34a',
    messagingSenderId: '543297399935',
    projectId: 'soulplan-dateplanner',
    authDomain: 'soulplan-dateplanner.firebaseapp.com',
    databaseURL: 'https://soulplan-dateplanner-default-rtdb.firebaseio.com',
    storageBucket: 'soulplan-dateplanner.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuglgklOUcCkyeKyUx_PtDvud3NWGj4-4',
    appId: '1:543297399935:android:a00c55db93fc9f975da34a',
    messagingSenderId: '543297399935',
    projectId: 'soulplan-dateplanner',
    databaseURL: 'https://soulplan-dateplanner-default-rtdb.firebaseio.com',
    storageBucket: 'soulplan-dateplanner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdTjl9VCsnos9-PQxIe2Kbf_KgqFiGNgQ',
    appId: '1:543297399935:ios:74642b18481e4fa55da34a',
    messagingSenderId: '543297399935',
    projectId: 'soulplan-dateplanner',
    databaseURL: 'https://soulplan-dateplanner-default-rtdb.firebaseio.com',
    storageBucket: 'soulplan-dateplanner.appspot.com',
    androidClientId: '543297399935-iq1usbkk96s5qce6ba1584p3nqtqu6ti.apps.googleusercontent.com',
    iosClientId: '543297399935-p6uok0eef2r2nefrhsolqbuchsp9ancs.apps.googleusercontent.com',
    iosBundleId: 'com.aifun.dateideas.planadate',
  );
}
